stages:
  - build
  - release


build:
  image: docker:20.10.16
  # run on a gitlab-runner that is configured with docker-in-docker
  tags:
    - dind
  stage: build
  except:
    - tags
  services:
    - docker:20.10.16-dind
  variables:
    # use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    # mounts /certs directory for the service and build container
    # needed for the Docker client to use the certificates
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # use previous image as a cache to speedup build process
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .

build:tagged:
  image: docker:20.10.16
  # run on a gitlab-runner that is configured with docker-in-docker
  tags:
    - dind
  stage: build
  # only for git tags
  only:
    - tags
  services:
    - docker:20.10.16-dind
  variables:
    # use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    # mounts /certs directory for the service and build container
    # needed for the Docker client to use the certificates
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # use previous image as a cache to speedup build process
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - echo $CI_COMMIT_TAG > public/VERSION
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'



